### ISSUE TITLE
No formulae are linked

### ISSUE THREAD

**Issue by papatistos** [alfredapp/alias-homebrew-apps-workflow#1]
I seem to be misunderstanding how this workflow is supposed to work. When I run the workflow, it doesn't  make any of the homebrew apps available. The output it produces is 

```
[23:27:01.548] Logging Started...
[23:27:43.040] Alias Homebrew Apps[External] Processing complete
[23:27:43.045] Alias Homebrew Apps[External] Passing output '' to Run Script
[23:28:08.483] Alias Homebrew Apps[Keyword] Processing complete
[23:28:08.489] Alias Homebrew Apps[Keyword] Passing output '' to Run Script
```

The formulae variable is left empty in the workflow settings.

ANd these are the formulae I currently have:

```
brew list
==> Formulae
briss			graphite2		libx11			lz4			wakeonlan
cairo			harfbuzz		libxau			lzo			xorgproto
fontconfig		icu4c			libxcb			mupdf-tools		xz
freetype		jpeg-turbo		libxdmcp		openjdk			zstd
gettext			libpng			libxext			pcre2
giflib			libpthread-stubs	libxrender		pixman
glib			libtiff			little-cms2		pkg-config

```

My expectation was that when I run the workflow, typing "briss" in Alfred search, it would find `briss`as an appl. But this is not what it's supposed to do, is it?

**Comment by vitorgalvao** [comment]
> My expectation was that when I run the workflow, typing "briss" in Alfred search, it would find `briss`as an appl. But this is not what it's supposed to do, is it?

It is not. The workflow is for formula *which already produce .app bundles* to have those linked in a way that Spotlight’s indexing and thus Alfred can find them when doing regular searches.
