### ISSUE TITLE
Wrong id

### ISSUE THREAD

**Issue by renald** [alfredapp/alias-homebrew-apps-workflow#2]
### Workflow version

2022.6

### Alfred version

5.0.6

### macOS version

13.1

### Debugger output

```alfred_debugger
-
```

### More details

The script expects the id 'com.alfredapp.aliashomebrewapps', but the workflow is installed with the id 'com.alfredapp.vitor.aliashomebrewapps'.

**Comment by vitorgalvao** [comment]
Nice catch, thank you. The README has been fixed and the update will be live soon.
